### ISSUE TITLE
issue 11: Delete Category

### ISSUE THREAD

**Issue by RohmaAr** [RohmaAr/SQE#11]
Deleting a category is not possible. The button is not functional.
login as the admin
Admin selects any category.
click "Delete Category" button.

**Comment by AliAhsan69** [comment]
The issue has been resolved 
1. Login as the admin 
2. click manage category 
3. click delete button 
4. New updated categories will be shown after deletion 
before deletion:
![WhatsApp Image 2023-12-01 at 00 04 33_9cd21da0](https://github.com/RohmaAr/SQE/assets/102369293/83805d11-6942-4bac-9e82-75fd5792dda1)
after deletion:
![WhatsApp Image 2023-12-01 at 00 04 32_5d1c189a](https://github.com/RohmaAr/SQE/assets/102369293/6f1af33e-5b0f-4968-b757-a2ca9df95fdf)
changes to the codes in categoryservice.java:
![Screenshot 2023-12-01 005933](https://github.com/RohmaAr/SQE/assets/102369293/685b3da7-c0f2-45f9-9e30-5922b95e6146)
changes to the codes in categoryDao.java:
![Screenshot 2023-12-01 010055](https://github.com/RohmaAr/SQE/assets/102369293/7c6d2417-c104-40d9-868f-99d27dd2afcc)

**Comment by AliAhsan69** [comment]
The issue has been resolved. 
1. Login as the admin 
2. select categories 
3. press the delete option
4. A dialogue box will be shown asking whether you want to delete the category or not?
5. press the yes button
6. category will be deleted
![Screenshot 2023-12-01 023243](https://github.com/RohmaAr/SQE/assets/102369293/2bb00ce9-f243-4133-9842-03988252e4ea)
![Screenshot 2023-12-01 023257](https://github.com/RohmaAr/SQE/assets/102369293/ae7cc1d3-59cd-4dec-9f01-300084645355)
following changes were made in the categories.jsp:
<td>
                        <form action="/admin/categories/delete" method="post" onsubmit="return confirm('Are you sure you want to delete this category?')">
                            <input type="hidden" name="id" value="${category.id}">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
in categoryDao:
@Transactional
	public boolean deleteCategory(int id) {
		Category categoryToDelete = sessionFactory.getCurrentSession().get(Category.class, id);

		if (categoryToDelete != null) {
			sessionFactory.getCurrentSession().delete(categoryToDelete);
			return true;
		}

		return false;
	}
in catogory service: 
@Transactional
	public Boolean deleteCategory(int id) {
		return this.categoryDao.deleteCategory(id);
	}
in admin controller:
@PostMapping("categories/delete")
	public String removeCategoryDb(@RequestParam("id") int id) {
		this.categoryService.deleteCategory(id);
		return "redirect:/admin/categories";
	}
changes were also made to the schema with respect to foreign key constraints:
-- SQL configs


-- create database and use it
CREATE DATABASE IF NOT EXISTS ecommjava;
USE ecommjava;

-- create the category table
CREATE TABLE IF NOT EXISTS CATEGORY(
  category_id int unique key not null auto_increment primary key,
  name        varchar(255) null
);

-- insert default categories
INSERT INTO CATEGORY(name) VALUES 
  ('Fruits'),
  ('Vegetables'),
  ('Meat'),
  ('Fish'),
  ('Dairy'),
  ('Bakery'),
  ('Drinks'),
  ('Sweets'),
  ('Other');

-- create the customer table
CREATE TABLE IF NOT EXISTS CUSTOMER(
  id       int unique key not null auto_increment primary key,
  address  varchar(255) null,
  email    varchar(255) null,
  password varchar(255) null,
  role     varchar(255) null,
  username varchar(255) null
);

-- insert default customers
INSERT INTO CUSTOMER(address, email, password, role, username) VALUES
  ('123, Albany Street', 'admin@nyan.cat', '123', 'ROLE_ADMIN', 'admin'),
  ('765, 5th Avenue', 'lisa@gmail.com', '765', 'ROLE_NORMAL', 'lisa');

-- create the product table
CREATE TABLE IF NOT EXISTS PRODUCT(
  product_id  int unique key not null auto_increment primary key,
  description varchar(255) null,
  image       varchar(255) null,
  name        varchar(255) null,
  price       int null,
  quantity    int null,
  weight      int null,
  category_id int null,
  customer_id int null,
  CONSTRAINT FK7u438kvwr308xcwr4wbx36uiw FOREIGN KEY (category_id) REFERENCES CATEGORY(category_id) ON DELETE CASCADE
);

-- insert default products
INSERT INTO PRODUCT(description, image, name, price, quantity, weight, category_id) VALUES
  ('Fresh and juicy', 'https://freepngimg.com/save/9557-apple-fruit-transparent/744x744', 'Apple', 3, 40, 76, 1),
  ('Woops! There goes the eggs...', 'https://www.nicepng.com/png/full/813-8132637_poiata-bunicii-cracked-egg.png', 'Cracked Eggs', 1, 90, 43, 9);

-- create indexes
CREATE INDEX FK7u438kvwr308xcwr4wbx36uiw ON PRODUCT (category_id);
CREATE INDEX FKt23apo8r9s2hse1dkt95ig0w5 ON PRODUCT (customer_id);
