### ISSUE TITLE
issue 12: Adding Category 

### ISSUE THREAD

**Issue by RohmaAr** [RohmaAr/SQE#12]
Not functional. Only allows user to enter the name, changes aren't saved in database and neither is there a page to display after
1.Login as the admin
2.press the manage button in the category box
3.press the add category button
3.Enter the name of the category
4.press save changes

**Comment by AliAhsan69** [comment]
Issue has been resolved.
1. Login as the admin 
2. Select the catgory button
3. press add category 
4. enter the name of the category 
5. the category will be saved 
![Screenshot 2023-12-01 033606](https://github.com/RohmaAr/SQE/assets/102369293/d4f2f0ec-b238-4d6d-9fdd-c905218ac278)
![Screenshot 2023-12-01 033633](https://github.com/RohmaAr/SQE/assets/102369293/632d9d6e-23ee-46fc-87b1-87edf6e434f6)
![Screenshot 2023-12-01 033657](https://github.com/RohmaAr/SQE/assets/102369293/d838033b-2c88-4797-a582-450701b5717e)

following changes were made 
admincontroller: 
![Screenshot 2023-12-01 033252](https://github.com/RohmaAr/SQE/assets/102369293/157bf595-3e68-4967-b99a-cf0d5d5fe648)
categoryservice:
![Screenshot 2023-12-01 033358](https://github.com/RohmaAr/SQE/assets/102369293/0849d8b3-0109-49ef-a4ff-df4d7f6823a2)
category dao:
![Screenshot 2023-12-01 033442](https://github.com/RohmaAr/SQE/assets/102369293/7834f374-4d15-4067-ae6d-a460cdd6d98b)
