### ISSUE TITLE
issue 13: Update Product 

### ISSUE THREAD

**Issue by RohmaAr** [RohmaAr/SQE#13]
The update button is not functional. There is no output when the button is pressed

Login as the admin
press the manages button in the products box
press the update button

**Comment by AliAhsan69** [comment]
The issue has been resolved.
Before resolving issue:
1. login as the admin
2. select manage products 
3. a whitelabal error page will apperar
![Screenshot 2023-12-01 123212](https://github.com/RohmaAr/SQE/assets/102369293/341fc5ce-60b7-47d5-a527-f576a8762b41)
after solving issue:
1. Login as the admin 
2. Select manage products 
3. a page will appear where you can edit all the info about the product 
5. make your desired changes 
6. then press update changes button 
7. the product info will be updated
![Screenshot 2023-12-01 123249](https://github.com/RohmaAr/SQE/assets/102369293/21a765f0-0182-400c-b31b-0b18241d3ba2)
![Screenshot 2023-12-01 123315](https://github.com/RohmaAr/SQE/assets/102369293/973288b2-aa68-4a2e-935f-ce90df578acc)
![Screenshot 2023-12-01 123858](https://github.com/RohmaAr/SQE/assets/102369293/75b92ee6-bfc7-41c8-8ee0-8d3be3985458)
