### ISSUE TITLE
issue 15: Confirmation messages(New feature)

### ISSUE THREAD

**Issue by fatimahehe** [RohmaAr/SQE#15]
Human computer interactions rules have not been followed, the user will be annoyed while using the website

**Comment by AliAhsan69** [comment]
We have added different dialogue boxes on logout buttons and while choosing to delete or something that is important.
![Screenshot 2023-12-01 023243](https://github.com/RohmaAr/SQE/assets/102369293/0a67de9b-5a31-43cf-b207-5cf3b3b1cab4)
![WhatsApp Image 2023-11-30 at 01 00 35_10a69e66](https://github.com/RohmaAr/SQE/assets/102369293/a521e1a3-e14f-4187-bc64-f01d7e1a91c2)

**Comment by AliAhsan69** [comment]
Warnings have been added aswell.
![Screenshot 2023-12-01 024222](https://github.com/RohmaAr/SQE/assets/102369293/3dec3adc-9247-44e1-bf67-b634ea63dc89)

**Comment by AliAhsan69** [comment]
more helpful screenshots.
![WhatsApp Image 2023-12-01 at 02 47 06_9e5ccfbb](https://github.com/RohmaAr/SQE/assets/102369293/26fe03dc-d0dd-4686-a99f-0a24ae488bcb)
