### ISSUE TITLE
Issue 16: Contact page(New Feature)

### ISSUE THREAD

**Issue by fatimahehe** [RohmaAr/SQE#16]
The contact page is not available 
login as a customer 
press the contact us button
nothing is displayed

**Comment by RohmaAr** [comment]
The navbar now has an option to allow users to communicate with the admin via email.
Some additions were made in the index.jsp and UseController, userdao and userservice class to fetch the admin's email
![mail to front end](https://github.com/RohmaAr/SQE/assets/102350775/84b67ce5-11d8-4454-8ed7-8af7c83ae26f)
![getmail](https://github.com/RohmaAr/SQE/assets/102350775/bd6ef187-2143-4efc-be6b-416040fc0eb2)

This is how it appears in the first page (index.jsp). Upon clicking the link, the email application on the user's desktop prompts user to sign in and then the following draft is displayed where the recepient (admin's) email is already entered

![getmailface](https://github.com/RohmaAr/SQE/assets/102350775/aa2a3011-3302-43f1-b5fa-20a3a7da40c2)

![once you sign in](https://github.com/RohmaAr/SQE/assets/102350775/29c1b1fb-2a13-4f8e-9aff-1b0ce3015306)
