### ISSUE TITLE
issue 2: user with same credentials can register as many times as they want

### ISSUE THREAD

**Issue by AliAhsan69** [RohmaAr/SQE#2]
After the registration for the 3rd user is successfull, the user can use the same name and info to register again without any problem.

Click on "Regiter here" button
Enter same credentials for two different users
The system will allow you to register both the users

**Comment by RohmaAr** [comment]
The system was allowing users to register with the same credentials more than once. The attached branch now ensures that the user registers with a unique username and email. In case such conditions aren't met, a modal is displayed, showing an error message.
The added functions isEmailUnique(User user) and isUserUnique(User user) functions of user in turn return userDao's function of the same name that return boolean value after checking if the passed user's email and username already exist in database
![register code change](https://github.com/RohmaAr/SQE/assets/102350775/c8fda178-62b4-4faf-8073-143412dce68b)
![register modal](https://github.com/RohmaAr/SQE/assets/102350775/10d9eddd-5da5-4c2b-85d0-cc518f56bbf1)
![controller changes register](https://github.com/RohmaAr/SQE/assets/102350775/8c169475-9270-4bc4-a838-58355551e940)

![error for same email](https://github.com/RohmaAr/SQE/assets/102350775/066fb1ff-1cef-46e5-beba-e1da1b6af68f)
![error for same username ](https://github.com/RohmaAr/SQE/assets/102350775/bf03b149-b740-4825-a38f-5d8eb2af3b54)
