### ISSUE TITLE
issue 3: No limit on credentials

### ISSUE THREAD

**Issue by AliAhsan69** [RohmaAr/SQE#3]
When regitering for new user The user can enter any length of charcater in email password and name field
There shoud be some limit to how many charcter user should enter for new registration.
Also there is no check if the email is valid or not, you can enter whatever you like.
1.open the homepage
2.Enter whatever you like in the name field and password field

**Comment by fatimahehe** [comment]
This Issue has been solved, a constraint has been added to the username to make it atleast 3 characters long and a constraint on password to make it atleast 6 characters long and at maximum 20. Input will stop after reaching 20 characters for the password.
1. Open http://localhost:8080/register
2. Enter your username("Should be atleast 3 characters long")
3. Enter password("Should be atleast 6 characters long and maximum 20 characters long")
4. Enter your email
5. Enter your address
6. click register 
7. Generates a login page 
8. Enter your info that you used to register your account
9. it will generate the products page
![Screenshot 2023-11-30 002124](https://github.com/RohmaAr/SQE/assets/147590838/0cee223d-1fc8-4529-a026-c6e174646ff5)

![lengthen password](https://github.com/RohmaAr/SQE/assets/147590838/263bb662-188b-4315-bdeb-5ec0a8e6f18b)
![WhatsApp Image 2023-11-30 at 01 00 36_52989125](https://github.com/RohmaAr/SQE/assets/147590838/9cc5b458-fe6e-4908-81b4-a88d9849f469)
![Screenshot 2023-11-30 002109](https://github.com/RohmaAr/SQE/assets/147590838/53db8770-7bd5-43ac-ab4b-b55215dd05f6)
